//! Generated by `rustereum add` (checked in for the example).
pub trait Ownable {
    const SOL_NAME: &'static str = "Ownable";
    const SOL_IMPORT: &'static str = "@openzeppelin/contracts/access/Ownable.sol";
}
