//! Generated by `rustereum add` (checked in for the example).
pub trait AccessControl {
    const SOL_NAME: &'static str = "AccessControl";
    const SOL_IMPORT: &'static str = "@openzeppelin/contracts/access/AccessControl.sol";
}
