//! `rustereum` is an **experimental Rust DSL for EVM smart contracts**.
//!
//! You write contracts as ordinary Rust structs and `impl` blocks annotated
//! with `#[contract]`. rustereum lowers them to Solidity, compiles that with
//! `solc` (via [`foundry-compilers`](https://crates.io/crates/foundry-compilers))
//! to EVM bytecode, and lets you **inherit real OpenZeppelin contracts** through
//! Rust trait impls. Contracts are tested end-to-end in
//! [`revm`](https://crates.io/crates/revm) with a typed client generated by the
//! macro.
//!
//! > Status: a learning/experimental project, not audited or production-ready.
//! > The supported language is a small, deliberately-minimal subset (see
//! > [Supported language subset](#supported-language-subset) and
//! > [Limitations](#limitations)).
//!
//! # The compilation pipeline
//!
//! ```text
//! #[contract]  ──►  IR  ──►  Solidity  ──►  solc (foundry-compilers)  ──►  bytecode + ABI
//!    (proc macro)   (traits)  (lower)         │
//!                                             └─►  solc --ir  ──►  Yul (for inspection)
//! ```
//!
//! - The `#[contract]` proc macro (from the companion `rustereum-macros` crate)
//!   lowers your struct/impl into a small **intermediate representation** — see
//!   the [`ir`] module — exposed as generated trait impls
//!   ([`ContractStorage`], [`ContractMethods`],
//!   [`ContractInherits`]), and re-emits the original items
//!   so they still type-check as native Rust.
//! - [`assemble`] (and friends) reconstruct a whole [`Contract`]
//!   value from those trait impls.
//! - [`solidity::lower_solidity`] lowers the IR to **Solidity** source.
//! - The [`driver`] compiles that Solidity to **bytecode + ABI** via `solc`.
//!   Because inheritance, dispatch, ABI encoding, and reverts are all handled by
//!   `solc`, real OpenZeppelin contracts "just work" as base classes.
//! - Every compile writes inspectable artifacts to `target/rustereum/`:
//!   `<Name>.sol` (generated Solidity), `<Name>.yul` (the Yul IR `solc` emits),
//!   and `<Name>.json` (bytecode + ABI). See [`driver::Artifact`].
//! - The [`vm`] module is a small revm-free EVM abstraction the generated test
//!   clients call into; the `testing` module (behind the `testing` feature)
//!   provides the `revm`-backed implementation.
//!
//! # Quickstart
//!
//! A contract is a struct (its fields are storage) plus an `impl` (its methods):
//!
//! ```ignore
//! use rustereum::prelude::*;
//!
//! #[contract]
//! pub struct Counter {
//!     count: u256,
//! }
//!
//! #[contract]
//! impl Counter {
//!     pub fn increment(&mut self) {
//!         self.count += 1;
//!     }
//!
//!     pub fn get(&self) -> u256 {
//!         self.count
//!     }
//! }
//! ```
//!
//! The macro also generates a **typed client** and a `compile()` helper, so
//! tests drive the contract in an in-process EVM without hand-writing selectors
//! or ABI encoding:
//!
//! ```ignore
//! use rustereum::testing::InMemoryDB;   // revm's in-memory DB, re-exported
//! use rustereum::vm::{Address, U256};
//!
//! #[test]
//! fn counter_end_to_end() {
//!     let art = Counter::compile().expect("compile");   // Rust → Solidity → bytecode
//!     let mut evm = InMemoryDB::default();
//!
//!     let counter = Counter::deploy(&mut evm, &art);     // typed deploy → CounterClient
//!     assert_eq!(counter.get(&mut evm), U256::from(0));  // view: decoded return
//!     counter.increment(&mut evm, Address::from([0x11; 20])).unwrap();  // caller + Result
//!     assert_eq!(counter.get(&mut evm), U256::from(1));
//! }
//! ```
//!
//! View methods (`&self`) take just the evm and return the decoded value;
//! state-changing methods take an explicit `caller` and return
//! `Result<_, `[`Revert`](vm::Revert)`>` (so a rejected access-controlled call is
//! `Err`). `revm` is optional, behind the `testing` feature; the generated
//! client itself compiles without it.
//!
//! # Inheriting OpenZeppelin
//!
//! Inheritance is a **Rust trait impl**. Each imported Solidity contract has a
//! generated binding trait; implementing it declares the base.
//! `#[constructor(Parent(args))]` forwards constructor arguments to the base, and
//! `#[modifier(name)]` applies an inherited modifier:
//!
//! ```ignore
//! use crate::bindings::Ownable;
//! use rustereum::prelude::*;
//!
//! #[contract]
//! pub struct Counter { count: u256 }
//!
//! #[contract]
//! impl Ownable for Counter {}                       // inherit OZ Ownable
//!
//! #[contract]
//! impl Counter {
//!     #[constructor(Ownable(initial_owner))]        // → constructor(address initialOwner) Ownable(initialOwner)
//!     pub fn new(initial_owner: Address) {}
//!
//!     #[modifier(only_owner)]                        // → the inherited `onlyOwner` modifier
//!     pub fn increment(&mut self) { self.count += 1; }
//!
//!     pub fn get(&self) -> u256 { self.count }
//! }
//! ```
//!
//! # Modules
//!
//! - [`ir`] — the intermediate representation the macro produces and the rest of
//!   the crate consumes ([`Contract`], [`Method`](ir::Method),
//!   [`Field`](ir::Field), the `Contract*` traits, …).
//! - [`solidity`] — [`lower_solidity`](solidity::lower_solidity): IR → Solidity
//!   source.
//! - [`driver`] — Solidity → bytecode + ABI via `solc`
//!   ([`compile_contract`](driver::compile_contract), [`Artifact`](driver::Artifact)).
//! - [`vm`] — the revm-free [`Vm`](vm::Vm) trait the generated clients call, plus
//!   ABI [`selector`](vm::selector)/encode/decode helpers.
//! - `testing` — the `revm`-backed [`Vm`](vm::Vm) impl (feature `testing`).
//! - [`prelude`] — the handful of imports a contract module needs.
//!
//! # Supported language subset
//!
//! The supported subset (v1):
//!
//! | Category | Supported |
//! |---|---|
//! | Types (fields & params) | [`u256`], [`Address`], `bool` |
//! | Storage | struct fields (`self.field`) |
//! | Expressions | `self.field`, integer literals, `+` (`+=`, `=`) |
//! | Functions | `&self` (view) / `&mut self` (state-changing), typed params & return |
//! | Constructor | `#[constructor(Parent(args…))]` — args are param idents or string/int literals |
//! | Modifiers | `#[modifier(snake_case)]` (camelCased to match the inherited Solidity name) |
//! | Inheritance | `impl Parent for Contract {}` (single parent) |
//!
//! Identifiers are written `snake_case` in Rust and converted to `camelCase` in
//! the generated Solidity (so ABI selectors are idiomatic).
//!
//! # Limitations
//!
//! Not yet supported:
//!
//! - Only [`u256`]/[`Address`]/`bool` — no `string`/`bytes`/arrays as
//!   **parameter** types (string/number **literals** work as base-constructor
//!   args, which is why ERC20/721/1155 inherit fine).
//! - No arithmetic beyond `+`; no loops, locals, or conditionals in bodies.
//! - No **function overrides** with real bodies → contracts requiring overrides
//!   (e.g. `Governor`) can't be made concrete.
//! - No **interface implementation** or **external contract calls**.
//! - No calling inherited `internal` functions with arguments (e.g. `_mint(...)`).
//! - Single inheritance parent per contract.

pub mod driver;
pub mod ir;
pub mod solidity;
#[cfg(feature = "testing")]
pub mod testing;
pub mod vm;

/// The imports a `#[contract]` module needs: the DSL scalar types [`u256`] and
/// [`Address`], and the [`contract`](rustereum_macros::contract) attribute macro.
///
/// ```ignore
/// use rustereum::prelude::*;
/// ```
pub mod prelude {
    pub use crate::u256;
    pub use crate::Address;
    pub use rustereum_macros::contract;
}

use crate::ir::{Contract, ContractInherits, ContractMethods, ContractStorage, Parent};

/// Assemble the full [`Contract`] IR from a type's generated storage + methods
/// traits and its (already-resolved) `inherits` list. The base-constructor
/// argument bindings ([`ContractMethods::base_inits`]) are merged into the
/// matching parents' [`Parent::base_args`].
///
/// This is the lowest-level assembler; prefer [`assemble`] (standalone
/// contracts) or [`assemble_inheriting`] (contracts with a parent), which supply
/// the `inherits` list for you.
///
/// Callers pass `inherits` explicitly because whether a type inherits can only
/// be detected at a concrete type site (via the internal inheritance probe the
/// macro emits inline); a generic function cannot observe a type's
/// [`ContractInherits`] impl through an opaque `T`. That probe is exactly why
/// [`assemble_from`] and [`assemble_inheriting`] are split.
///
/// # Panics
///
/// Panics if a `#[constructor(Parent(..))]` names a `Parent` that is not present
/// in `inherits` (i.e. no matching `impl Parent for Self {}`).
pub fn assemble_from<T: ContractStorage + ContractMethods>(mut inherits: Vec<Parent>) -> Contract {
    let base = <T as ContractMethods>::base_inits();
    for p in inherits.iter_mut() {
        if let Some((_, args)) = base.iter().find(|(n, _)| n == &p.name) {
            p.base_args = args.clone();
        }
    }
    for (name, _) in &base {
        assert!(
            inherits.iter().any(|p| &p.name == name),
            "rustereum: #[constructor({name}(..))] names `{name}`, which is not inherited via `impl {name} for ...`"
        );
    }
    Contract {
        name: <T as ContractStorage>::name(),
        inherits,
        fields: <T as ContractStorage>::fields(),
        constructor: <T as ContractMethods>::constructor(),
        methods: <T as ContractMethods>::methods(),
    }
}

/// Assemble the IR for a standalone (non-inheriting) `#[contract]` type — a
/// convenience wrapper over [`assemble_from`] with an empty parent list.
pub fn assemble<T: ContractStorage + ContractMethods>() -> Contract {
    assemble_from::<T>(Vec::new())
}

/// Assemble the IR for an inheriting `#[contract]` type. The parent list comes
/// from the type's [`ContractInherits`] impl (generated by
/// `impl Parent for Self {}`), which is then passed to [`assemble_from`].
pub fn assemble_inheriting<T: ContractStorage + ContractMethods + ContractInherits>() -> Contract {
    assemble_from::<T>(<T as ContractInherits>::parents())
}

// ---------------------------------------------------------------------------
// Inheritance probe
//
// The `#[contract]` macro generates a `Self::compile()` that must work whether
// or not the contract inherits — but the inherent-impl expansion cannot see the
// separate `impl Parent for Self {}` trait impl. So the generated code probes at
// the *concrete* `Self` site: if `Self: ContractInherits`, the inherent method
// below wins (inherent methods outrank trait methods in resolution); otherwise
// the blanket `InheritsFallback` trait method returns an empty parent list.
// This resolution only works at a concrete type — not inside a generic fn —
// which is exactly why the macro emits it inline.
// ---------------------------------------------------------------------------

#[doc(hidden)]
pub struct InheritsProbe<T>(pub core::marker::PhantomData<T>);

#[doc(hidden)]
pub trait InheritsFallback {
    fn rustereum_parents(&self) -> Vec<Parent>;
}

impl<T> InheritsFallback for InheritsProbe<T> {
    fn rustereum_parents(&self) -> Vec<Parent> {
        Vec::new()
    }
}

impl<T: ContractInherits> InheritsProbe<T> {
    pub fn rustereum_parents(&self) -> Vec<Parent> {
        <T as ContractInherits>::parents()
    }
}

#[cfg(test)]
mod probe_tests {
    use super::*;
    use crate::ir::Parent;

    struct Inheriting;
    impl ContractInherits for Inheriting {
        fn parents() -> Vec<Parent> {
            vec![Parent {
                name: "Ownable".into(),
                import_path: "x".into(),
                base_args: vec![],
            }]
        }
    }

    struct Standalone;

    #[test]
    fn probe_resolves_both_ways() {
        // Bring the fallback trait into scope so its method is a candidate.
        use core::marker::PhantomData;

        let inheriting = InheritsProbe::<Inheriting>(PhantomData).rustereum_parents();
        assert_eq!(inheriting.len(), 1);
        assert_eq!(inheriting[0].name, "Ownable");

        let standalone = InheritsProbe::<Standalone>(PhantomData).rustereum_parents();
        assert!(standalone.is_empty());
    }
}

/// EVM address type. In a `#[contract]`, contract bodies are a DSL: this type
/// exists so constructor/method params typed `Address` type-check as native
/// Rust; the real on-chain semantics come from the generated Yul.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Address(pub alloy_primitives::Address);

/// EVM 256-bit unsigned integer. In a `#[contract]`, contract bodies are a
/// DSL: this type exists so they type-check as native Rust; the real
/// semantics come from the generated Yul, not these operator impls.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct u256(pub alloy_primitives::U256);

impl From<u64> for u256 {
    fn from(v: u64) -> Self {
        u256(alloy_primitives::U256::from(v))
    }
}

// Enables `self.count += 1` (the integer literal infers to u64).
impl core::ops::AddAssign<u64> for u256 {
    fn add_assign(&mut self, rhs: u64) {
        self.0 += alloy_primitives::U256::from(rhs);
    }
}

// The `+` operator impls below exist so DSL bodies that use binary `+`
// (e.g. `a + b`, `self.total + 10`) type-check as native Rust. The real
// on-chain semantics come from the generated Yul (`add(...)`), not these.

// u256 + u256
impl core::ops::Add for u256 {
    type Output = u256;
    fn add(self, rhs: u256) -> u256 {
        u256(self.0 + rhs.0)
    }
}

// u256 + <integer literal> (literal infers to u64)
impl core::ops::Add<u64> for u256 {
    type Output = u256;
    fn add(self, rhs: u64) -> u256 {
        u256(self.0 + alloy_primitives::U256::from(rhs))
    }
}
