pub mod driver;
pub mod ir;
pub mod solidity;
#[cfg(feature = "testing")]
pub mod testing;
pub mod vm;

pub mod prelude {
    pub use crate::u256;
    pub use crate::Address;
    pub use rustereum_macros::contract;
}

use crate::ir::{Contract, ContractInherits, ContractMethods, ContractStorage, Parent};

/// Assemble the full `Contract` IR from a type's generated storage + methods
/// traits and its (already-resolved) `inherits` list. The base-constructor
/// argument bindings (`base_inits`) are merged into the matching parents.
///
/// Callers pass `inherits` explicitly because whether a type inherits can only
/// be detected at a concrete type site (see [`InheritsProbe`]); a generic
/// function cannot observe a type's `ContractInherits` impl through opaque `T`.
pub fn assemble_from<T: ContractStorage + ContractMethods>(mut inherits: Vec<Parent>) -> Contract {
    let base = <T as ContractMethods>::base_inits();
    for p in inherits.iter_mut() {
        if let Some((_, args)) = base.iter().find(|(n, _)| n == &p.name) {
            p.base_args = args.clone();
        }
    }
    for (name, _) in &base {
        assert!(
            inherits.iter().any(|p| &p.name == name),
            "rustereum: #[constructor({name}(..))] names `{name}`, which is not inherited via `impl {name} for ...`"
        );
    }
    Contract {
        name: <T as ContractStorage>::name(),
        inherits,
        fields: <T as ContractStorage>::fields(),
        constructor: <T as ContractMethods>::constructor(),
        methods: <T as ContractMethods>::methods(),
    }
}

/// Assemble the IR for a standalone (non-inheriting) `#[contract]` type.
pub fn assemble<T: ContractStorage + ContractMethods>() -> Contract {
    assemble_from::<T>(Vec::new())
}

/// Assemble the IR for an inheriting `#[contract]` type (parents come from the
/// `ContractInherits` impl generated by the `impl Parent for Self {}`).
pub fn assemble_inheriting<T: ContractStorage + ContractMethods + ContractInherits>() -> Contract {
    assemble_from::<T>(<T as ContractInherits>::parents())
}

// ---------------------------------------------------------------------------
// Inheritance probe
//
// The `#[contract]` macro generates a `Self::compile()` that must work whether
// or not the contract inherits — but the inherent-impl expansion cannot see the
// separate `impl Parent for Self {}` trait impl. So the generated code probes at
// the *concrete* `Self` site: if `Self: ContractInherits`, the inherent method
// below wins (inherent methods outrank trait methods in resolution); otherwise
// the blanket `InheritsFallback` trait method returns an empty parent list.
// This resolution only works at a concrete type — not inside a generic fn —
// which is exactly why the macro emits it inline.
// ---------------------------------------------------------------------------

#[doc(hidden)]
pub struct InheritsProbe<T>(pub core::marker::PhantomData<T>);

#[doc(hidden)]
pub trait InheritsFallback {
    fn rustereum_parents(&self) -> Vec<Parent>;
}

impl<T> InheritsFallback for InheritsProbe<T> {
    fn rustereum_parents(&self) -> Vec<Parent> {
        Vec::new()
    }
}

impl<T: ContractInherits> InheritsProbe<T> {
    pub fn rustereum_parents(&self) -> Vec<Parent> {
        <T as ContractInherits>::parents()
    }
}

#[cfg(test)]
mod probe_tests {
    use super::*;
    use crate::ir::Parent;

    struct Inheriting;
    impl ContractInherits for Inheriting {
        fn parents() -> Vec<Parent> {
            vec![Parent {
                name: "Ownable".into(),
                import_path: "x".into(),
                base_args: vec![],
            }]
        }
    }

    struct Standalone;

    #[test]
    fn probe_resolves_both_ways() {
        // Bring the fallback trait into scope so its method is a candidate.
        use core::marker::PhantomData;

        let inheriting = InheritsProbe::<Inheriting>(PhantomData).rustereum_parents();
        assert_eq!(inheriting.len(), 1);
        assert_eq!(inheriting[0].name, "Ownable");

        let standalone = InheritsProbe::<Standalone>(PhantomData).rustereum_parents();
        assert!(standalone.is_empty());
    }
}

/// EVM address type. In a `#[contract]`, contract bodies are a DSL: this type
/// exists so constructor/method params typed `Address` type-check as native
/// Rust; the real on-chain semantics come from the generated Yul.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Address(pub alloy_primitives::Address);

/// EVM 256-bit unsigned integer. In a `#[contract]`, contract bodies are a
/// DSL: this type exists so they type-check as native Rust; the real
/// semantics come from the generated Yul, not these operator impls.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct u256(pub alloy_primitives::U256);

impl From<u64> for u256 {
    fn from(v: u64) -> Self {
        u256(alloy_primitives::U256::from(v))
    }
}

// Enables `self.count += 1` (the integer literal infers to u64).
impl core::ops::AddAssign<u64> for u256 {
    fn add_assign(&mut self, rhs: u64) {
        self.0 += alloy_primitives::U256::from(rhs);
    }
}

// The `+` operator impls below exist so DSL bodies that use binary `+`
// (e.g. `a + b`, `self.total + 10`) type-check as native Rust. The real
// on-chain semantics come from the generated Yul (`add(...)`), not these.

// u256 + u256
impl core::ops::Add for u256 {
    type Output = u256;
    fn add(self, rhs: u256) -> u256 {
        u256(self.0 + rhs.0)
    }
}

// u256 + <integer literal> (literal infers to u64)
impl core::ops::Add<u64> for u256 {
    type Output = u256;
    fn add(self, rhs: u64) -> u256 {
        u256(self.0 + alloy_primitives::U256::from(rhs))
    }
}
