//! Generated by `rustereum add` (checked in for the example).
pub trait ReentrancyGuard {
    const SOL_NAME: &'static str = "ReentrancyGuard";
    const SOL_IMPORT: &'static str = "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
}
