//! Generated by `rustereum add` (checked in for the example).
pub trait ERC20 {
    const SOL_NAME: &'static str = "ERC20";
    const SOL_IMPORT: &'static str = "@openzeppelin/contracts/token/ERC20/ERC20.sol";
}
