//! Generated by `rustereum add` (checked in for the example).
pub trait ERC1967Proxy {
    const SOL_NAME: &'static str = "ERC1967Proxy";
    const SOL_IMPORT: &'static str = "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
}
