//! Generated by `rustereum add` (checked in for the example).
pub trait Pausable {
    const SOL_NAME: &'static str = "Pausable";
    const SOL_IMPORT: &'static str = "@openzeppelin/contracts/utils/Pausable.sol";
}
