//! Generated by `rustereum add` (checked in for the example).
pub trait ERC721 {
    const SOL_NAME: &'static str = "ERC721";
    const SOL_IMPORT: &'static str = "@openzeppelin/contracts/token/ERC721/ERC721.sol";
}
