//! Generated by `rustereum add` (checked in for the example).
pub trait ERC165 {
    const SOL_NAME: &'static str = "ERC165";
    const SOL_IMPORT: &'static str = "@openzeppelin/contracts/utils/introspection/ERC165.sol";
}
