//! Library logic for the `rustereum` CLI: project scaffolding, git dependency
//! import, and Solidity → Rust trait binding generation.
//!
//! Everything here is plain functions so tests can call them directly; the
//! `main.rs` binary is a thin clap wrapper around these.

use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::Command;

/// The template contract dropped into a fresh project's `src/lib.rs`.
const TEMPLATE_LIB: &str = r#"//! A rustereum project. Edit this contract or add your own modules.

use rustereum::prelude::*;

#[contract]
pub struct Counter {
    count: u256,
}

#[contract]
impl Counter {
    pub fn increment(&mut self) {
        self.count += 1;
    }

    pub fn get(&self) -> u256 {
        self.count
    }
}

mod bindings;
"#;

/// Scaffold a fresh rustereum project skeleton at `target_dir`.
///
/// Creates `Cargo.toml`, `src/lib.rs` (a working template contract),
/// `src/bindings.rs`, `remappings.txt`, and an empty `lib/` directory.
///
/// If `target_dir` already exists and is non-empty, this refuses unless
/// `force` is set.
pub fn scaffold_new(target_dir: &Path, name: &str, force: bool) -> io::Result<()> {
    if target_dir.exists() {
        let non_empty = fs::read_dir(target_dir)?.next().is_some();
        if non_empty && !force {
            return Err(io::Error::new(
                io::ErrorKind::AlreadyExists,
                format!(
                    "target directory {} is not empty (use --force to overwrite)",
                    target_dir.display()
                ),
            ));
        }
    }

    let src = target_dir.join("src");
    fs::create_dir_all(&src)?;
    // Empty lib/ directory for git dependencies; .gitkeep so it survives VCS.
    let lib = target_dir.join("lib");
    fs::create_dir_all(&lib)?;
    fs::write(lib.join(".gitkeep"), "")?;

    // `rustereum = "0.1"` is a placeholder — rustereum is not published yet, so
    // consumers must repoint this at a path/git dependency for now.
    let cargo_toml = format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[dependencies]
# Placeholder: rustereum is not published yet. Point this at a path or git
# dependency (e.g. rustereum = {{ path = "../rustereum" }}) until it is.
rustereum = "0.1"
alloy-primitives = "0.8"

[dev-dependencies]
"#
    );
    fs::write(target_dir.join("Cargo.toml"), cargo_toml)?;
    fs::write(src.join("lib.rs"), TEMPLATE_LIB)?;
    fs::write(src.join("bindings.rs"), bindings_header())?;
    fs::write(target_dir.join("remappings.txt"), "")?;

    Ok(())
}

fn bindings_header() -> String {
    "//! Generated by `rustereum add`.\n".to_string()
}

/// Recursively collect all `.sol` file paths under `root`, sorted for
/// deterministic output.
fn collect_sol_files(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
        let Ok(entries) = fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                walk(&path, out);
            } else if path.extension().and_then(|e| e.to_str()) == Some("sol") {
                out.push(path);
            }
        }
    }
    walk(root, &mut out);
    out.sort();
    out
}

/// Extract contract/interface names declared in a Solidity source string.
///
/// Matches `contract Name`, `abstract contract Name`, and `interface Name`.
/// Skips `library`. This is a deliberately simple line scan — not a full
/// Solidity parser (YAGNI).
fn extract_declarations(source: &str) -> Vec<String> {
    let mut names = Vec::new();
    for raw in source.lines() {
        let line = raw.trim();
        let rest = if let Some(r) = line.strip_prefix("abstract contract ") {
            Some(r)
        } else if let Some(r) = line.strip_prefix("contract ") {
            Some(r)
        } else {
            line.strip_prefix("interface ")
        };
        if let Some(rest) = rest {
            if let Some(name) = parse_identifier(rest) {
                names.push(name);
            }
        }
    }
    names
}

/// Read a leading Solidity identifier from `s` (stops at the first char that
/// can't be part of an identifier, e.g. space, `{`, or `is`).
fn parse_identifier(s: &str) -> Option<String> {
    let ident: String = s
        .chars()
        .take_while(|c| c.is_alphanumeric() || *c == '_' || *c == '$')
        .collect();
    if ident.is_empty() || ident.chars().next().unwrap().is_numeric() {
        None
    } else {
        Some(ident)
    }
}

/// Generate Rust trait bindings for every contract/interface found under
/// `sol_root`. Each contract in `sol_root/<rel>` gets a trait whose
/// `SOL_IMPORT` is `<remap_prefix><rel>`.
///
/// Duplicate trait names (same contract name in multiple files) are emitted
/// once — the first occurrence wins.
pub fn generate_bindings(sol_root: &Path, remap_prefix: &str) -> String {
    let mut out = bindings_header();
    let mut seen: Vec<String> = Vec::new();

    for file in collect_sol_files(sol_root) {
        let rel = file
            .strip_prefix(sol_root)
            .unwrap_or(&file)
            .to_string_lossy()
            .replace('\\', "/");
        let import = format!("{remap_prefix}{rel}");
        let Ok(source) = fs::read_to_string(&file) else {
            continue;
        };
        for name in extract_declarations(&source) {
            if seen.contains(&name) {
                continue;
            }
            seen.push(name.clone());
            out.push_str(&format!(
                "pub trait {name} {{\n    const SOL_NAME: &'static str = \"{name}\";\n    const SOL_IMPORT: &'static str = \"{import}\";\n}}\n",
            ));
        }
    }

    out
}

/// Result of resolving how a cloned repo maps into Solidity import space.
struct Remap {
    /// Import prefix, e.g. `@openzeppelin/contracts/`.
    prefix: String,
    /// The remapping target relative to the project root, e.g.
    /// `lib/openzeppelin-contracts/contracts/`.
    target: String,
    /// Directory to scan for `.sol` files (absolute).
    sol_root: PathBuf,
}

fn resolve_remap(project_root: &Path, repo: &str) -> Remap {
    let clone_dir = format!("lib/{repo}");
    let has_contracts = project_root.join(&clone_dir).join("contracts").is_dir();

    // Special-case OpenZeppelin so canonical `@openzeppelin/contracts/...`
    // imports resolve. This is the one remapping that must work verbatim.
    if repo == "openzeppelin-contracts" && has_contracts {
        return Remap {
            prefix: "@openzeppelin/contracts/".to_string(),
            target: format!("{clone_dir}/contracts/"),
            sol_root: project_root.join(&clone_dir).join("contracts"),
        };
    }

    if has_contracts {
        Remap {
            prefix: format!("@{repo}/"),
            target: format!("{clone_dir}/contracts/"),
            sol_root: project_root.join(&clone_dir).join("contracts"),
        }
    } else {
        Remap {
            prefix: format!("@{repo}/"),
            target: format!("{clone_dir}/"),
            sol_root: project_root.join(&clone_dir),
        }
    }
}

/// Derive the repository name from a `owner/repo` GitHub spec.
fn repo_name(github_spec: &str) -> &str {
    github_spec
        .trim_end_matches(".git")
        .rsplit('/')
        .next()
        .unwrap_or(github_spec)
}

/// Clone a GitHub Solidity dependency into `lib/<repo>`, register its
/// remapping, and (re)generate its trait bindings into `src/bindings.rs`.
pub fn add_dependency(
    project_root: &Path,
    github_spec: &str,
    git_ref: Option<&str>,
) -> io::Result<()> {
    let repo = repo_name(github_spec);
    let clone_target = project_root.join("lib").join(repo);

    fs::create_dir_all(project_root.join("lib"))?;

    if clone_target.exists() {
        return Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            format!("dependency already present at {}", clone_target.display()),
        ));
    }

    let url = format!(
        "https://github.com/{}.git",
        github_spec.trim_end_matches(".git")
    );
    let mut cmd = Command::new("git");
    cmd.arg("clone").arg("--depth").arg("1");
    if let Some(r) = git_ref {
        cmd.arg("--branch").arg(r);
    }
    cmd.arg(&url).arg(&clone_target);

    let status = cmd
        .status()
        .map_err(|e| io::Error::other(format!("failed to run git: {e}")))?;
    if !status.success() {
        return Err(io::Error::other(format!(
            "git clone of {url} failed (status {status})"
        )));
    }

    let remap = resolve_remap(project_root, repo);

    // Append the remapping line if not already present (idempotent).
    let remap_line = format!("{}={}", remap.prefix, remap.target);
    append_line_if_absent(&project_root.join("remappings.txt"), &remap_line)?;

    // Generate bindings for the newly added dependency.
    let generated = generate_bindings(&remap.sol_root, &remap.prefix);
    let trait_count = generated.matches("pub trait ").count();
    if trait_count == 0 {
        eprintln!(
            "warning: no contracts/interfaces found under {} — bindings unchanged",
            remap.sol_root.display()
        );
        return Ok(());
    }

    merge_bindings(&project_root.join("src").join("bindings.rs"), &generated)?;
    Ok(())
}

/// Append `line` to the file at `path` if it is not already present. Creates
/// the file if missing.
fn append_line_if_absent(path: &Path, line: &str) -> io::Result<()> {
    let existing = fs::read_to_string(path).unwrap_or_default();
    if existing.lines().any(|l| l.trim() == line) {
        return Ok(());
    }
    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(path)?;
    if !existing.is_empty() && !existing.ends_with('\n') {
        writeln!(file)?;
    }
    writeln!(file, "{line}")?;
    Ok(())
}

/// Merge freshly generated trait definitions into an existing bindings file,
/// skipping any trait name already defined there.
fn merge_bindings(path: &Path, generated: &str) -> io::Result<()> {
    let existing = fs::read_to_string(path).unwrap_or_else(|_| bindings_header());

    // Collect trait names already present.
    let existing_traits: Vec<String> = existing
        .lines()
        .filter_map(|l| l.trim().strip_prefix("pub trait "))
        .filter_map(parse_identifier)
        .collect();

    // Split the generated output into per-trait blocks and keep only new ones.
    let mut additions = String::new();
    let mut current: Option<(String, String)> = None; // (name, block)
    for line in generated.lines() {
        if let Some(rest) = line.trim().strip_prefix("pub trait ") {
            // Flush previous block.
            if let Some((name, block)) = current.take() {
                if !existing_traits.contains(&name) {
                    additions.push_str(&block);
                }
            }
            let name = parse_identifier(rest).unwrap_or_default();
            current = Some((name, format!("{line}\n")));
        } else if let Some((_, block)) = current.as_mut() {
            block.push_str(line);
            block.push('\n');
        }
        // Header / blank lines before the first trait are ignored.
    }
    if let Some((name, block)) = current.take() {
        if !existing_traits.contains(&name) {
            additions.push_str(&block);
        }
    }

    if additions.is_empty() {
        return Ok(());
    }

    let mut merged = existing;
    if !merged.ends_with('\n') {
        merged.push('\n');
    }
    merged.push_str(&additions);
    fs::write(path, merged)
}

/// Locate a project root: `start` if it contains `remappings.txt`, otherwise
/// walk upward until one is found. Falls back to `start` if none exists.
pub fn find_project_root(start: &Path) -> PathBuf {
    let mut dir = start;
    loop {
        if dir.join("remappings.txt").exists() {
            return dir.to_path_buf();
        }
        match dir.parent() {
            Some(parent) => dir = parent,
            None => return start.to_path_buf(),
        }
    }
}
