//! Generated by `rustereum add` (checked in for the example).
pub trait ERC1155 {
    const SOL_NAME: &'static str = "ERC1155";
    const SOL_IMPORT: &'static str = "@openzeppelin/contracts/token/ERC1155/ERC1155.sol";
}
